find_path(HIDAPI_INCLUDE_DIR NAMES hidapi.h PATH_SUFFIXES hidapi)
find_library(HIDAPI_LIBRARY  NAMES hidapi hidapi-hidraw hidapi-libusb)
set(HIDAPI_LIBRARIES  ${HIDAPI_LIBRARY})
set(HIDAPI_INCLUDE_DIRS ${HIDAPI_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(HIDAPI DEFAULT_MSG HIDAPI_LIBRARY HIDAPI_INCLUDE_DIR)

mark_as_advanced(HIDAPI_INCLUDE_DIR HIDAPI_LIBRARY)

if(HIDAPI_FOUND)
  if(NOT TARGET HIDAPI::HIDAPI)
    add_library(HIDAPI::HIDAPI UNKNOWN IMPORTED)
    set_target_properties(HIDAPI::HIDAPI PROPERTIES
      IMPORTED_LOCATION ${HIDAPI_LIBRARY}
      INTERFACE_INCLUDE_DIRECTORIES ${HIDAPI_INCLUDE_DIR}
    )
  endif()
endif()
